export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const CHANGE_AVATAR_SUCCESS = "CHANGE_AVATAR_SUCCESS";
export const CHANGE_AVATAR_FAIL = "CHANGE_AVATAR_FAIL";

const settingsTypes = {
  EDIT_PROFILE_SUCCESS,
  EDIT_PROFILE_FAIL,
  GET_USER_SUCCESS,
  GET_USER_FAIL,
  CHANGE_PASSWORD_SUCCESS,
  CHANGE_PASSWORD_FAIL,
  CHANGE_AVATAR_SUCCESS,
  CHANGE_AVATAR_FAIL,
};

export default settingsTypes;
